import { CSSProperties } from "react";

export const TOKEN = {
  bg: "#060608",
  phone: "#0C0C12",
  text: "#F0EEE5",
  textSub: "#D0CEC8",
  textFaint: "#C8C6C0",
  muted: "#44445A",
  dim: "#55556A",
  border: "#28283A",
  borderSub: "#1A1A24",
  amber: "#EF9F27",
  amberText: "#412402",
  danger: "#E24B4A",
  success: "#1D9E75",
  mono: "'JetBrains Mono', monospace",
};

export const S: { [key: string]: CSSProperties } = {
  root: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    background: TOKEN.bg,
    padding: 16,
  },
  phone: {
    width: 360,
    maxWidth: "100%",
    background: TOKEN.phone,
    borderRadius: 40,
    border: `2px solid ${TOKEN.border}`,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minHeight: 720,
    boxShadow: "0 40px 80px rgba(0,0,0,0.7)",
  },
  statusBar: {
    background: TOKEN.phone,
    padding: "14px 22px 8px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
  },
  statusTime: { color: "#D8D6CE", fontSize: 12, fontWeight: 500, fontFamily: "monospace" },
  notch: { width: 80, height: 14, background: "#18181F", borderRadius: 20, border: "0.5px solid #28283A" },
  homeBar: { padding: "8px 0 14px", display: "flex", justifyContent: "center", flexShrink: 0, background: TOKEN.phone },
  homeIndicator: { width: 100, height: 4, background: TOKEN.border, borderRadius: 2 },
  body: { flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" },
  screen: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    padding: 24,
  },
  screenPad: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: 20,
    overflowY: "auto" as "auto",
    gap: 12,
  },
  screenBase: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflowY: "auto" as "auto",
  },
  biometricBtn: {
    width: 84,
    height: 84,
    borderRadius: "50%",
    background: "#171720",
    border: `1.5px solid ${TOKEN.amber}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    outline: "none",
  },
  pinDot: {
    width: 44,
    height: 50,
    background: "#16161F",
    borderRadius: 10,
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  lastSession: {
    padding: "10px 20px",
    background: "#16161F",
    borderRadius: 20,
    border: `0.5px solid ${TOKEN.border}`,
  },
  row: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  label: { color: TOKEN.muted, fontSize: 11 },
  heading: { color: TOKEN.text, fontSize: 18, fontWeight: 500 },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "#16161F",
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    outline: "none",
  },
  voiceBox: {
    background: "#0D0D17",
    borderRadius: 16,
    border: `0.5px solid ${TOKEN.amber}`,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
  },
  voiceRing: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    border: `2px solid ${TOKEN.amber}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  voiceResult: {
    background: "#16161F",
    borderRadius: 10,
    padding: "10px 14px",
    width: "100%",
    textAlign: "center",
  },
  confirmBtn: {
    width: "100%",
    padding: "11px",
    background: TOKEN.amber,
    border: "none",
    borderRadius: 10,
    color: TOKEN.amberText,
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
  },
  catGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 9,
  },
  catBtn: {
    borderRadius: 14,
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 6,
    cursor: "pointer",
    textAlign: "left",
    border: "0.5px solid #2E2E3E",
    outline: "none",
  },
  picon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  card: {
    background: "#16161F",
    borderRadius: 14,
    padding: 14,
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  cardRow: {
    background: "#16161F",
    borderRadius: 12,
    padding: "11px 14px",
    border: `0.5px solid ${TOKEN.border}`,
    display: "flex",
    alignItems: "center",
    gap: 11,
    position: "relative",
    overflow: "hidden",
  },
  noteInput: {
    background: "transparent",
    border: "none",
    color: TOKEN.textSub,
    fontSize: 14,
    outline: "none",
    fontFamily: "inherit",
    width: "100%",
  },
  adjBtn: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: "#252530",
    border: "0.5px solid #3A3A4A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#888",
    fontSize: 14,
    outline: "none",
  },
  fineBtn: {
    padding: "5px 11px",
    borderRadius: 20,
    background: "#252530",
    border: "0.5px solid #3A3A4A",
    color: "#888",
    fontSize: 12,
    cursor: "pointer",
  },
  presetBtn: {
    padding: "7px 14px",
    borderRadius: 20,
    background: "#1C1C28",
    border: "0.5px solid #2E2E3E",
    color: TOKEN.textFaint,
    fontSize: 12,
    cursor: "pointer",
    fontFamily: TOKEN.mono,
  },
  primaryBtn: {
    width: "100%",
    padding: 15,
    background: TOKEN.amber,
    border: "none",
    borderRadius: 14,
    color: TOKEN.amberText,
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    letterSpacing: "0.02em",
  },
  tabRow: {
    display: "flex",
    background: "#16161F",
    borderRadius: 10,
    padding: 3,
    gap: 2,
  },
  deleteSlide: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 64,
    background: TOKEN.danger,
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: 20,
  },
  fab: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: TOKEN.amber,
    padding: "12px 28px",
    borderRadius: 30,
    border: "none",
    cursor: "pointer",
    boxShadow: "0 8px 24px rgba(239, 159, 39, 0.2)",
  },
  toggle: {
    width: 40,
    height: 22,
    borderRadius: 11,
    border: "none",
    cursor: "pointer",
    position: "relative",
    flexShrink: 0,
  },
  knob: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#fff",
    position: "absolute",
    top: 2,
    transition: "left 0.2s",
  },
  sectionLabel: {
    color: TOKEN.amber,
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    padding: "20px 20px 8px",
  },
  togRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    borderBottom: `0.5px solid ${TOKEN.borderSub}`,
  },
  keypadGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 16,
    width: "100%",
    maxWidth: 280,
    margin: "0 auto",
  },
  keyBtn: {
    height: 64,
    borderRadius: "50%",
    background: "#16161F",
    border: `0.5px solid ${TOKEN.border}`,
    color: TOKEN.text,
    fontSize: 22,
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    outline: "none",
    transition: "background 0.2s, transform 0.1s",
  },
  shakeAnim: {
    animation: "shake 0.4s ease-in-out",
  },
  dangerBtn: {
    width: "100%",
    padding: 12,
    background: "#1A1A24",
    border: `0.5px solid ${TOKEN.border}`,
    borderRadius: 10,
    color: TOKEN.danger,
    fontSize: 13,
    cursor: "pointer",
  },
};
