export const S: { [key: string]: React.CSSProperties } = {
  root: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    background: "#060608",
    padding: 16,
  },
  phone: {
    width: 360,
    maxWidth: "100%",
    background: "#0C0C12",
    borderRadius: 40,
    border: "2px solid #28283A",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minHeight: 720,
    boxShadow: "0 40px 80px rgba(0,0,0,0.7)",
  },
  statusBar: {
    background: "#0C0C12",
    padding: "14px 22px 8px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
  },
  statusTime: { color: "#D8D6CE", fontSize: 12, fontWeight: 500, fontFamily: "monospace" },
  notch: { width: 80, height: 14, background: "#18181F", borderRadius: 20, border: "0.5px solid #28283A" },
  homeBar: { padding: "8px 0 14px", display: "flex", justifyContent: "center", flexShrink: 0, background: "#0C0C12" },
  homeIndicator: { width: 100, height: 4, background: "#28283A", borderRadius: 2 },
  body: { flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" },
  screen: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    padding: 24,
    background: "#0C0C12",
  },
  screenPad: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: 20,
    background: "#0C0C12",
    overflowY: "auto" as "auto",
  },
  screenBase: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    background: "#0C0C12",
  },
  biometricBtn: {
    width: 84,
    height: 84,
    borderRadius: "50%",
    background: "#171720",
    border: "1.5px solid #EF9F27",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  pinDot: {
    width: 44,
    height: 50,
    background: "#16161F",
    borderRadius: 10,
    border: "0.5px solid #28283A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  lastSession: {
    padding: "10px 20px",
    background: "#16161F",
    borderRadius: 20,
    border: "0.5px solid #28283A",
  },
  row: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  label: { color: "#44445A", fontSize: 11 },
  heading: { color: "#F0EEE5", fontSize: 18, fontWeight: 500 },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "#16161F",
    border: "0.5px solid #28283A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  todayBanner: {
    background: "#16161F",
    borderRadius: 12,
    padding: "14px 16px",
    border: "0.5px solid #28283A",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  voiceBox: {
    background: "#0D0D17",
    borderRadius: 16,
    border: "0.5px solid #EF9F27",
    padding: 16,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
  },
  voiceRing: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    border: "2px solid #EF9F27",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  voiceResult: {
    background: "#16161F",
    borderRadius: 10,
    padding: "10px 14px",
    width: "100%",
    textAlign: "center",
  },
  confirmBtn: {
    width: "100%",
    padding: "11px",
    background: "#EF9F27",
    border: "none",
    borderRadius: 10,
    color: "#412402",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
  },
  catGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 9,
    flex: 1,
  },
  catBtn: {
    background: "#1A1A24",
    border: "0.5px solid #2E2E3E",
    borderRadius: 14,
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 6,
    cursor: "pointer",
    textAlign: "left",
  },
  picon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  card: {
    background: "#16161F",
    borderRadius: 14,
    padding: 14,
    border: "0.5px solid #28283A",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  noteInput: {
    background: "transparent",
    border: "none",
    color: "#D0CEC8",
    fontSize: 14,
    outline: "none",
    fontFamily: "inherit",
    width: "100%",
  },
  adjBtn: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: "#252530",
    border: "0.5px solid #3A3A4A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#888",
    fontSize: 14,
  },
  fineBtn: {
    padding: "5px 11px",
    borderRadius: 20,
    background: "#252530",
    border: "0.5px solid #3A3A4A",
    color: "#888",
    fontSize: 12,
    cursor: "pointer",
  },
  presetBtn: {
    padding: "7px 14px",
    borderRadius: 20,
    background: "#1C1C28",
    border: "0.5px solid #2E2E3E",
    color: "#C8C6C0",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "monospace",
  },
  primaryBtn: {
    width: "100%",
    padding: 15,
    background: "#EF9F27",
    border: "none",
    borderRadius: 14,
    color: "#412402",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    letterSpacing: "0.02em",
  },
  tabRow: {
    display: "flex",
    background: "#16161F",
    borderRadius: 10,
    padding: 3,
    gap: 2,
  },
  tabBtn: {
    flex: 1,
    padding: "7px",
    borderRadius: 8,
    border: "none",
    fontSize: 12,
    cursor: "pointer",
  },
  expRow: {
    background: "#16161F",
    borderRadius: 12,
    padding: "11px 14px",
    border: "0.5px solid #28283A",
    display: "flex",
    alignItems: "center",
    gap: 11,
    position: "relative",
    overflow: "hidden",
    cursor: "pointer",
  },
  deleteSlide: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 64,
    background: "#A32D2D",
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: 20,
  },
  fab: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#EF9F27",
    padding: "12px 28px",
    borderRadius: 30,
    border: "none",
    cursor: "pointer",
  },
  toggle: {
    width: 40,
    height: 22,
    borderRadius: 11,
    border: "none",
    cursor: "pointer",
    position: "relative",
    flexShrink: 0,
  },
  knob: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#fff",
    position: "absolute",
    top: 2,
  },
};
